### ISSUE TITLE
Get tracking number from reference number; or get list of shipments

### ISSUE THREAD

**Issue by yanpozka** [jzempel/fedex#5]
Can we get the tracking number from a reference number with this library ? or is possible to get a list of all my packages that are not delivered ?
Thanks in advance

**Comment by jzempel** [comment]
@yanpozka this library is basically a thin wrapper around some of the most basic FedEx services. You can extend `BaseService` to access and use any of the web services documented in the [FedEx Developer Guide](https://images.fedex.com/templates/components/apps/wpor/secure/downloads/pdf/201607/FedEx_WebServices_DevelopersGuide_v2016.pdf).
